### PR TITLE
Add support for custom title text style for all widgets

### PR DESCRIPTION
**Pull request by nicejhkim**

### CODE REVIEW

**Comment by GAM3RG33K** [comment]
That's a clean fix, thanks a lot for the contribution.

**Comment by vptcnt** [comment]
Hi,
It is possible to test this version ?
Could you push it on ppub.dev ?

**Comment by vptcnt** [comment]
@nicejhkim 

Thanks for your pull. What about SettingsGroup ?
The style is frozen too. Could be good to add a TextStyle too ?

**Comment by nicejhkim** [comment]
@vptcnt 
I made an additional PR which includes SettingsGroup, ExpandableSettingsTIle and TextInputSettingsTile.

**Pull request merged**
