### PR TITLE
Add adaptive widgets and Add more usable settings screen

### PR DESCRIPTION
**Pull request by AhmedAbouelkher**
- Add adaptive switches for IOS devices in `lib/src/settings_screen.dart` and `example/lib/main.dart`.
- Add an adaptive slider for IOS devices in `lib/src/settings_screen.dart`.
- Modified Scaffold to ensure easy implementation with Scaffold-ready screens in `lib/src/settings_screen.dart`.
- Add `drawer` and `endDrawer` to the settings screen Scaffold in `lib/src/settings_screen.dart`.
- Add `isMainScreen` as an optional argument to `SettingsScreen` widget in `lib/src/settings_screen.dart`;  to give the developer the choice between having a ready setting screen or just rendering the settings screen widgets with no Scaffold or AppBar.

### CODE REVIEW

**Comment by GAM3RG33K** [comment]
@AhmedAbouelkher The idea of having a scaffold ready settings screen is awesome. I want to check it out ASAP.
Thanks for contributing.

**Comment by GAM3RG33K** [comment]
Please update your forked master branch to latest from main branch and then resolve the conflicts. otherwise, it will be difficult to merge your changes in main code.

**Comment by AhmedAbouelkher** [comment]
> I have checked the changes you made.
> 
> Apart from using `.adaptive` versions of Slider and switched, I found some changes to be kind of irrelevant or too specific for a single use case.
> 
> 1. Addition of Drawer to show in main settings screen:
>    
>    * Initially I thought the children will be shown as they were before but drawer will put some additional navigational help to navigate through each settings group in the page easily without scrolling the settings page.
>    * showing the children in the drawer only is not commonly a useful scenario as a developer expects to add many settings in a page which is why a settings screen is created.
>      For one or two settings, developers can import required settings tiles in their regular drawer to achieve the same result like this.
>    * please tell me if I misunderstood something that you wanted to achieve with this change.
> 2. Change in slider setting code specific to volume:
>    
>    * I saw that there is one more flag introduced as `isMuted` which is very specific to slider being used for volume, however slider setting is a general purpose widget just like every other widget in this package.
>    * You can add a volume specific widget as an additional widget with existing slider widget and your implementation of mute button. We already have maney additional widgets like this, `SimpleDropdownSettings`, `SimpleRadioSettings`, etc.
> 3. There's an unused value `isIOS` that is not removed. As a general tip I would suggest you to check for unused code before committing to VCS 😄 .

Hi,
Thanks for the advice.
Overall I don't think that anyone would mind setting his own `Scaffold` and `AppBar` in the `Settings Screen`, I have just made some modifications like adding `isMainScreen` to be able not to break the older versions of the package with such a modification.
I think in the future you should remove the `Scaffold` because in its situation is considered unnecessary to the screen.

**Comment by GAM3RG33K** [comment]
@AhmedAbouelkher If you can provide, individual pull requests for each feature separately that would be great. 

It speeds up the inspect & merge process.
I am closing this pull request.

Thanks for contributing. :innocent:

**Pull request closed without merging**
